<a href="https://colab.research.google.com/github/LucMoura/Oficina_CD/blob/main/C%C3%B3pia_de_aula03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intro

- DataFrame **Sentment140**
  -  Qual é o sentimento predominante (positivo ou negativo)?
  -  Como o sentimento varia ao longo do tempo?

# Pandas

O pandas é uma ferramenta que permite a manipulação de DataFrames de forma simples!

Com ele podemos acissar indices e fazer alterações nos DataFrames.

In [ ]:
import pandas as pd

# Sentment140

[Link para Download do DataSet.](https://www.kaggle.com/datasets/kazanova/sentiment140)

**Colunas:**
- *target:* A polaridade do tweet (0 = negativo, 4 = positivo);

- *ids:* Representa o id do tweet;

- *date:* A data em que tweet foi feito(Sat May 16 23:58:44 UTC 2009)

- *flag:* The query (lyx). If there is no query, then this value is NO_QUERY.

- *user:* Nome do usuario que tweetou (robotickilldozr)

- *text:* Conteudo do tweet (Lyx is cool)

> Como eu transformo meu DataSet em um DataFrame?

- Para isso usamos o **Pandas**, que permite a manipulação des grandes volumes de dados.

## Importando meu DataSet

>Lembre-se de realizar o **dowload** pelo link acima, e certificar-se de fazer o **upload** do arquivo para o seu **GoogleDrive**

In [ ]:
# Biblioteca pra conexão com o drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

- E como eu uso ele no meu código?

In [ ]:
# Carregar o dataset para um dataframe no pandas
dataset_path = '/content/drive/MyDrive/training.1600000.processed.noemoticon.csv'  # Substitua pelo seu caminho do arquivo CSV
df = pd.read_csv(dataset_path, encoding='latin-1') # enconding que suporta dados
                                  # de linguas ocidentais como ingles e portugues

In [ ]:
display(df)

,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer. You shoulda got David Carr of Third Day to do it. ;D"
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew
...,...,...,...,...,...,...
1599994,4,2193601966,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,AmandaMarie1028,Just woke up. Having no school is the best fee...
1599995,4,2193601969,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,TheWDBoards,TheWDB.com - Very cool to hear old Walt interv...
1599996,4,2193601991,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,bpbabe,Are you ready for your MoJo Makeover? Ask me f...
1599997,4,2193602064,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,tinydiamondz,Happy 38th Birthday to my boo of alll time!!! ...
1599998,4,2193602129,Tue Jun 16 08:40:50 PDT 2009,NO_QUERY,RyanTrevMorris,happy #charitytuesday @theNSPCC @SparksCharity...

# Visualizando meus dados

A biblioteca do Pandas, permite diversas formas de explorar e manipular as informações do nosso DataFrame.

Ao decorrer da nossa oficina, iremos explorar diversas funções de exploração e manipulação de dados usando o Pnadas.

Ferramentas de exploração do Pandas:
- .head(x)
- .tail()
- .info()
- .describe()
- .shape
- .columns
- .dtypes
- .isnull()
- .value_counts()
- uniquw()

In [ ]:
# Visualizando as primeiras linhas
df.head()

,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer. You shoulda got David Carr of Third Day to do it. ;D"
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew

In [ ]:
# Visualizando as ultimas linhas
df.tail()

,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer. You shoulda got David Carr of Third Day to do it. ;D"
1599994,4,2193601966,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,AmandaMarie1028,Just woke up. Having no school is the best fee...
1599995,4,2193601969,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,TheWDBoards,TheWDB.com - Very cool to hear old Walt interv...
1599996,4,2193601991,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,bpbabe,Are you ready for your MoJo Makeover? Ask me f...
1599997,4,2193602064,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,tinydiamondz,Happy 38th Birthday to my boo of alll time!!! ...
1599998,4,2193602129,Tue Jun 16 08:40:50 PDT 2009,NO_QUERY,RyanTrevMorris,happy #charitytuesday @theNSPCC @SparksCharity...

> Colunas

In [ ]:
# Visualizando as colunas
df.columns

Index(['0', '1467810369', 'Mon Apr 06 22:19:45 PDT 2009', 'NO_QUERY',
       '_TheSpecialOne_',
       '@switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer.  You shoulda got David Carr of Third Day to do it. ;D'],
      dtype='object')

In [ ]:
# alterando o nome das colunas
df.columns = ['target', 'id', 'date', 'flag', 'user', 'text']
print(df.columns)
df.head()

Index(['target', 'id', 'date', 'flag', 'user', 'text'], dtype='object')

,target,id,date,flag,user,text
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew

> Resumo dos dados

In [ ]:
# Resumo do DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599999 entries, 0 to 1599998
Data columns (total 6 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   target  1599999 non-null  int64
 1   id      1599999 non-null  int64
 2   date    1599999 non-null  object
 3   flag    1599999 non-null  object
 4   user    1599999 non-null  object
 5   text    1599999 non-null  object
dtypes: int64(2), object(4)
memory usage: 73.2+ MB

> Estatísticas descritivas

In [ ]:
# Estatísticas descritivas sobre as colunas
df.describe()

             target            id
count  1.599999e+06  1.599999e+06
mean   2.000001e+00  1.998818e+09
std    2.000001e+00  1.935757e+08
min    0.000000e+00  1.467811e+09
25%    0.000000e+00  1.956916e+09
50%    4.000000e+00  2.002102e+09
75%    4.000000e+00  2.177059e+09
max    4.000000e+00  2.329206e+09

In [ ]:
# Formato do dataframe, linhas e colunas
print("Dimensões: ", df.shape)
print("Linhas: ", df.shape[0])
print("Colunas: ", df.shape[1])

Dimensões:  (1599999, 6)
Linhas:  1599999
Colunas:  6

> Distribuição e Tipagem dos dados

In [ ]:
# Tipagem dos dados, inteiros, booleanos e etc
df.dtypes

target     int64
id         int64
date      object
flag      object
user      object
text      object
dtype: object

In [ ]:
# Verificando ausência de valores
df.isnull().sum()

target    0
id        0
date      0
flag      0
user      0
text      0
dtype: int64

In [ ]:
# Visualizando o balanceamento da coluna target
df['target'].value_counts()

target
4    800000
0    799999
Name: count, dtype: int64

# Praticando

> Agora, explore o DataSet do kaggle que contem o preço do aluguel de diversos imoveis no Brasil, e analise suas propriedades

[Link para o DataSet](https://www.kaggle.com/datasets/rubenssjr/brasilian-houses-to-rent/data)

> Após fazer o download, siga as mesmas etapas feitas com DataFrame *Sentment140*

In [ ]:
segundo_path = '/content/drive/MyDrive/houses_to_rent_v2.csv'  # Substitua pelo seu caminho do arquivo CSV
df_casas = pd.read_csv(segundo_path)

In [ ]:
# Visualizando as primeiras linhas
df_casas.head()

,city,area,rooms,bathroom,parking spaces,floor,animal,furniture,hoa (R$),rent amount (R$),property tax (R$),fire insurance (R$),total (R$)
0,São Paulo,70,2,1,1,7,acept,furnished,2065,3300,211,42,5618
1,São Paulo,320,4,4,0,20,acept,not furnished,1200,4960,1750,63,7973
2,Porto Alegre,80,1,1,1,6,acept,not furnished,1000,2800,0,41,3841
3,Porto Alegre,51,2,1,0,2,acept,not furnished,270,1112,22,17,1421
4,São Paulo,25,1,1,0,1,not acept,not furnished,0,800,25,11,836

In [ ]:
# Visualizando as ultimas linhas
df_casas.tail()

,city,area,rooms,bathroom,parking spaces,floor,animal,furniture,hoa (R$),rent amount (R$),property tax (R$),fire insurance (R$),total (R$)
10687,Porto Alegre,63,2,1,1,5,not acept,furnished,402,1478,24,22,1926
10688,São Paulo,285,4,4,4,17,acept,not furnished,3100,15000,973,191,19260
10689,Rio de Janeiro,70,3,3,0,8,not acept,furnished,980,6000,332,78,7390
10690,Rio de Janeiro,120,2,2,2,8,acept,furnished,1585,12000,279,155,14020
10691,São Paulo,80,2,1,0,-,acept,not furnished,0,1400,165,22,1587

In [ ]:
# Visualizando as colunas
df_casas.columns

Index(['city', 'area', 'rooms', 'bathroom', 'parking spaces', 'floor',
       'animal', 'furniture', 'hoa (R$)', 'rent amount (R$)',
       'property tax (R$)', 'fire insurance (R$)', 'total (R$)'],
      dtype='object')

In [ ]:
# Resumo do DataFrame
df_casas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10692 entries, 0 to 10691
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   city                 10692 non-null  object
 1   area                 10692 non-null  int64
 2   rooms                10692 non-null  int64
 3   bathroom             10692 non-null  int64
 4   parking spaces       10692 non-null  int64
 5   floor                10692 non-null  object
 6   animal               10692 non-null  object
 7   furniture            10692 non-null  object
 8   hoa (R$)             10692 non-null  int64
 9   rent amount (R$)     10692 non-null  int64
 10  property tax (R$)    10692 non-null  int64
 11  fire insurance (R$)  10692 non-null  int64
 12  total (R$)           10692 non-null  int64
dtypes: int64(9), object(4)
memory usage: 1.1+ MB

In [ ]:
# Estatísticas descritivas sobre as colunas
df_casas.describe()

,area,rooms,bathroom,parking spaces,hoa (R$),rent amount (R$),property tax (R$),fire insurance (R$),total (R$)
count,10692.000000,10692.000000,10692.000000,10692.000000,1.069200e+04,10692.000000,10692.000000,10692.000000,1.069200e+04
mean,149.217920,2.506079,2.236813,1.609147,1.174022e+03,3896.247194,366.704358,53.300879,5.490487e+03
std,537.016942,1.171266,1.407198,1.589521,1.559231e+04,3408.545518,3107.832321,47.768031,1.648473e+04
min,11.000000,1.000000,1.000000,0.000000,0.000000e+00,450.000000,0.000000,3.000000,4.990000e+02
25%,56.000000,2.000000,1.000000,0.000000,1.700000e+02,1530.000000,38.000000,21.000000,2.061750e+03
50%,90.000000,2.000000,2.000000,1.000000,5.600000e+02,2661.000000,125.000000,36.000000,3.581500e+03
75%,182.000000,3.000000,3.000000,2.000000,1.237500e+03,5000.000000,375.000000,68.000000,6.768000e+03
max,46335.000000,13.000000,10.000000,12.000000,1.117000e+06,45000.000000,313700.000000,677.000000,1.120000e+06

In [ ]:
# Formato do dataframe, linhas e colunas
# Exibindo as colunas
print(f"Dimensões: {df_casas.shape}")
print(f"Linhas: {df_casas.shape[0]}")
print(f"Colunas: {df_casas.shape[1]}")

Dimensões: (10692, 13)
Linhas: 10692
Colunas: 13

In [ ]:
# Tipagem dos dados, inteiros, booleanos e etc
df_casas.dtypes

city                   object
area                    int64
rooms                   int64
bathroom                int64
parking spaces          int64
floor                  object
animal                 object
furniture              object
hoa (R$)                int64
rent amount (R$)        int64
property tax (R$)       int64
fire insurance (R$)     int64
total (R$)              int64
dtype: object

In [ ]:
# Verificando ausência de valores
df_casas.isnull().sum()

city                   0
area                   0
rooms                  0
bathroom               0
parking spaces         0
floor                  0
animal                 0
furniture              0
hoa (R$)               0
rent amount (R$)       0
property tax (R$)      0
fire insurance (R$)    0
total (R$)             0
dtype: int64

> Bônus

In [ ]:
# identifique quais dados estão presentes nas colunas 'animais' e 'furniture'
df_casas['animal', 'furniture'].value_counts()

KeyError: ('animal', 'furniture')

# Target

As colunas alvo, ou apenas **Target**, sáo o enfoque do nosso problema.

> É a partir dela, que definimos nosso objetivo com aqueles dados, seja identificar sentimentos em cima de textos ou prever preço de casas.

In [ ]:
print("Primeiras linhas da coluna alvo: ")
df['target'].head()

Primeiras linhas da coluna alvo:

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [ ]:
print("Primeiras linhas da coluna alvo: ")
df_casas['total (R$)'].head()

Primeiras linhas da coluna alvo:

0    5618
1    7973
2    3841
3    1421
4     836
Name: total (R$), dtype: int64

# DIferentes Objetivos com DataSets

- Qual a prícipal diferença entre as colunas **target** dos dois DataFrames?

>Existem dois tipos príncipais de problemas evolvendo conjuntos de dados, problemas de **Classificação** e probelmas de **Regressão.**

## Classificação $\text{x}$ Regressão

- **Classificação:** Os problemas normalmente envolvem classificar as variaveis em dois grupos, geramente $[0, 1]$. Dessa forma, nosso objetivo é identificar os padrões que envolvem a escolha de determinado grupo.
- **Regressão:** Diferente da classificação, aqui estamos tentando encontrar a melhor relação entre as variaveis para prever um valor **contínuo**, ou seja, um valor indeterminado com intervalos infinitos.

> Com base neste conhecimento, é possivel identificar que nosso **DataFrame de tweets**, estão divididos em  **dois grupos**(Positivos e Negativos), sendo assim, um problema de **Classificação**.

> Já o DataFrame sobre preço de **imóveis**, está relacioando variaveis para determinar um **valor contínuo**(Velor do aluguel), dessa forma identificamos um problema de **Regressão**.

---
---

# Ações em Cima dos Dados

O que observar em meus DataFrames além do **Target**?
- Valores vazios
- Valores não numéricos
- Desbalanceamento de classes e Transformações

> As tomadas de decisões em cima destes critérios é o que forma a base de um bom Ciêntista de Dados, e, chamamos esta etapa de Pré-Processamento, ou em alguns casos, ETL.

## Imputação

Imputação consiste na técninca de lidar com valores vazios, seja removendo suas linhas, ou as substituindo pela média, moda ou mediana.

> Como vimos anteriormente, ac colunas *floor, animal e furniture* são variaveis do tipo Object, **texto**. Vamos explorar elas com mais detalhes.

In [ ]:
# Visualizando os valores unicos em cada coluna
df_casas[['animal', 'furniture', 'floor']].unique()

In [ ]:
df_casas.isnull().sum()

> Verificamos as colunas textuais, pois nelas, valores vazios podem não serem exibidos na função `.isnull()`

- Mesmo com valores vazios na coluna *'floor'*, eles não foram computados por conta de não estarem categorizados como **NAN**.

In [ ]:
df_casas['floor'].value_counts()

- Para ser possível a imputação, precisamos converter estes valores vazios para NAN.

> Para isso, transformaremos o ' - ' em NAN, tornando possível a imputação de valores vazios pela média ou dropar mais fácil.

In [ ]:
import numpy as np

In [ ]:
df_casas['floor'] = df_casas['floor'].replace('-', np.nan)

In [ ]:
df_casas['floor'].value_counts()

In [ ]:
df_casas.isnull().sum()

> Agora podemos tomar decisões sobre como tratar estes valores vazios.

- **Média**
  - Desvio Padrão
- **Moda**
- **Mediana**
- **Remoção Total:** Remoção de todos os valores faltantes, importante para colunas inuteis.

In [ ]:
df_casas.shape

In [ ]:
# Decisão de substituir pela média
df_casas.fillna(df_casas['floor'].mean(), inplace=True)

In [ ]:
# Decisão de substituir pela moda
df_casas.fillna(df_casas['floor'].mode()[0], inplace=True)

In [ ]:
# Decisão de substituir pela mediana
df_casas.fillna(df_casas['floor'].median(), inplace=True)

In [ ]:
# Decisão de remover os valores vazios
df_casas.dropna(subset=['floor'], inplace=True)

In [ ]:
print(df_casas.shape)
df_casas.isnull().sum()

### Praticando

> Agora, verifiquem a existência de valores vazios no DataFrame Sentiment140 usando `isnull()` e `sum()`.

*OBS: Lembrem de colocar o nome da variável correspondente ao estabelecido para o DataFrame Sentment140.*